/**
 * TOPICA CMS Database Schema Types
 * Contract Version: v1.0-custom-cms
 * Corresponds to migrations/001_initial_schema.sql
 */

/** Shared timestamp types for consistent API usage */
export type CoreColumnBase = {
  id?: string; // UUID primary key, auto-generated by PostgreSQL
};

export interface Timestamps {
  created_at: Date | number; // TIMESTAMPTZ stored as ISO string or timestamp
  updated_at: Date | number;
}

/** User role enumeration with validation */
export type UserRole = "admin" | "editor" | "contributor" | "reviewer" | "publisher";

/** Content kind enumeration */
export type ContentKind = "article" | "page" | "program" | "policy" | "admission";

/** Locale enumeration */
export type Locale = "vi" | "en";

/** Lead status enumeration */
export type LeadStatus = "new" | "contacted" | "qualified" | "converted" | "declined" | "excluded";

/** Publication action enumeration */
export type PublicationAction =
  | "draft"
  | "in_review"
  | "approved"
  | "published"
  | "unpublished"
  | "scheduled"
  | "expired"
  | "restored";

/** Site route kind enumeration */
export type RouteKind = "page" | "redirect" | "dynamic" | "system" | "error";

/** Route status code range: 200-599 */
export type StatusCode = number & { readonly __statusCodeBrand: unique symbol };

/** Schema version for content revisions */
export type SchemaVersion = "v1" | string;

/** Template key for content rendering */
export type TemplateKey = string;

/** Extended timestamp allowing future timestamps (for scheduling) */
export type ExtendedTimestamp = Date | number | string;

/** JSONB types for flexible content storage */
export interface BlocksJSON {
  blocks: unknown[];
  schema_version?: SchemaVersion;
}

export interface BaseUser extends CoreColumnBase, Timestamps {}

/**
 * User table - Hệ thống quản trị viên CMS
 */
export interface User extends BaseUser {
  username: string; // UNIQUE constraint (MAXLEN: 255)
  password_hash: string;
  name: string; // MAXLEN: 255
  role: UserRole;
  session_version: number;
}

/**
 * Categories table - Phân loại nội dung (có thể phân cấp cha-con)
 */
export interface Category extends CoreColumnBase, Timestamps {
  name: string; // MAXLEN: 255
  slug: string; // UNIQUE constraint (MAXLEN: 255)
  parent_id?: string; // UUID, optional for root categories
}

/**
 * Content items table - Đối tượng nội dung chính
 */
export interface ContentItem extends CoreColumnBase, Timestamps {
  kind: ContentKind;
  locale: Locale;
  title?: string;
  slug?: string; // MAXLEN: 255, optional for WYSIWYG editors
  excerpt?: string;
  published_revision_id?: string; // UUID, optional (set NULL when no published version)
  draft_revision_id?: string; // UUID, optional (current draft revision)
  archived_at?: Date | number; // Optional field for soft-archived content
  created_by?: string; // UUID, references users.id
}

/**
 * Content revisions table - Historie phiên bản nội dung
 */
export interface ContentRevision extends CoreColumnBase {
  content_id: string; // UUID, FK to content_items
  revision_no: number;
  schema_version: SchemaVersion;
  title?: string;
  excerpt?: string;
  template_key?: TemplateKey;
  blocks_json: BlocksJSON;
  legacy_html?: string;
  seo_title?: string;
  seo_description?: string;
  created_by?: string; // UUID, references users.id
}

/**
 * Content categories mapping table - Quan hệ nhiều-nhiều Content ↔ Category
 */
export type ContentCategory = {
  content_id: string; // UUID, FK to content_items (PRIMARY KEY column)
  category_id: string; // UUID, FK to categories (PRIMARY KEY column)
};

/**
 * Site routes table - Registry đường dẫn website
 */
export interface SiteRoute extends CoreColumnBase {
  locale: Locale;
  normalized_path: string; // MAXLEN: 512, UNIQUE per locale
  content_id?: string; // UUID, optional (can point to content or be system route)
  system_key?: string; // Optional system identifier (e.g., '/admin')
  route_kind: RouteKind;
  target_path?: string;
  status_code?: StatusCode;
}

/**
 * Leads table - Dữ liệu khách quan tâm từ form/tư vấn
 */
export interface Lead extends CoreColumnBase, Timestamps {
  full_name: string; // MAXLEN: 255
  phone: string; // MAXLEN: 20 (with international prefix)
  email?: string;
  program_code?: string;
  campus?: string; // MAXLEN: 100
  note?: string;
  status: LeadStatus;
  ip_hash: string; // CHAR(64), used for IP privacy
}

/**
 * Publication events table - Audit trail cho các hành động xuất bản
 */
export interface PublicationEvent extends CoreColumnBase, Timestamps {
  content_id: string; // UUID, FK to content_items
  revision_id: string; // UUID, FK to content_revisions
  action: PublicationAction;
  actor_id?: string; // UUID, optional (anonymous actions)
  reason?: string;
}

/**
 * Schema export for easy usage
 */
